name: Build JSON

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build JSON
      run: |
        ./convert_to_json.rb
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: map-data
        path: map_data.json